export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_ALL_PRODUCTS_LOADING = "GET_ALL_PRODUCTS_LOADING";
export const PRODUCT_LOADING_STARTS = "PRODUCT_LOADING_STARTS";
export const PRODUCT_LOADING_ENDS = "PRODUCT_LOADING_ENDS";

export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const EDIT_PRODUCT_LOADING_STARTS = "EDIT_PRODUCT_LOADING_STARTS";
export const EDIT_PRODUCT_LOADING_ENDS = "EDIT_PRODUCT_LOADING_ENDS";

export const GET_ERRORS = "GET_ERRORS";
